apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"patientmatch"},"name":"patientmatch","namespace":"patientmatch"},"spec":{"ports":[{"name":"http","nodePort":31081,"port":3000,"targetPort":3000}],"selector":{"app":"patientmatch"},"type":"NodePort"}}
  creationTimestamp: "2026-07-23T02:08:56Z"
  labels:
    app.kubernetes.io/instance: patientmatch
  name: patientmatch
  namespace: patientmatch
  resourceVersion: "2193397"
  uid: 165c0913-918c-4e5f-b2be-aa2879a9c2eb
spec:
  clusterIP: 10.68.78.196
  clusterIPs:
  - 10.68.78.196
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 31081
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: patientmatch
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
