apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"supabase-meta","namespace":"supabase"},"spec":{"ports":[{"name":"http","port":8080,"protocol":"TCP","targetPort":8080}],"selector":{"app":"supabase-meta"},"sessionAffinity":"None","type":"ClusterIP"}}
  creationTimestamp: "2026-07-28T12:01:53Z"
  name: supabase-meta
  namespace: supabase
  resourceVersion: "2211150"
  uid: 14964510-02ad-4fcb-8d14-76a477c965ec
spec:
  clusterIP: 10.68.5.158
  clusterIPs:
  - 10.68.5.158
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: supabase-meta
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
