apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"supabase-kong","namespace":"supabase"},"spec":{"externalTrafficPolicy":"Cluster","ports":[{"name":"proxy","nodePort":31082,"port":8000,"protocol":"TCP","targetPort":8000},{"name":"admin","port":8001,"protocol":"TCP","targetPort":8001}],"selector":{"app":"supabase-kong"},"sessionAffinity":"None","type":"NodePort"}}
  creationTimestamp: "2026-07-28T12:01:53Z"
  name: supabase-kong
  namespace: supabase
  resourceVersion: "2211156"
  uid: e47258b6-3172-488d-8907-f03f2b221554
spec:
  clusterIP: 10.68.45.5
  clusterIPs:
  - 10.68.45.5
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: proxy
    nodePort: 31082
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: admin
    nodePort: 32649
    port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    app: supabase-kong
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
