apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"supabase-rest","namespace":"supabase"},"spec":{"ports":[{"name":"http","port":3000,"protocol":"TCP","targetPort":3000}],"selector":{"app":"supabase-rest"},"sessionAffinity":"None","type":"ClusterIP"}}
  creationTimestamp: "2026-07-28T12:01:53Z"
  name: supabase-rest
  namespace: supabase
  resourceVersion: "2211146"
  uid: 5a4cbd3f-317b-493b-8edf-5c597332fe54
spec:
  clusterIP: 10.68.168.148
  clusterIPs:
  - 10.68.168.148
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: supabase-rest
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
