apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"supabase-db","namespace":"supabase"},"spec":{"ports":[{"name":"postgres","port":5432,"protocol":"TCP","targetPort":5432}],"selector":{"app":"supabase-db"},"sessionAffinity":"None","type":"ClusterIP"}}
  creationTimestamp: "2026-07-28T12:01:53Z"
  name: supabase-db
  namespace: supabase
  resourceVersion: "2211129"
  uid: cbfb64c5-e1cf-49ba-98ae-15107fd2cf1e
spec:
  clusterIP: 10.68.243.234
  clusterIPs:
  - 10.68.243.234
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: supabase-db
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
