apiVersion: v1
kind: Service
metadata:
  name: patientmatch
  namespace: patientmatch
spec:
  type: NodePort
  selector:
    app: patientmatch
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 31081
